### PR TITLE
Added the ability to set a database per Model (branch v2.0.0)

### PR DESCRIPTION
**Pull request by Flambe**
We use multiple databases in our Mongo set up. This pull request allows the database to be set on a per model basis. If no database is set, it falls back to the default as to not break backwards compatibility.

[Requires PR60 from mongolid](https://github.com/leroy-merlin-br/mongolid/pull/60)

### CODE REVIEW

**Comment by gmsantos** [comment]
Hi @Flambe, could you rebase your PR to master branch?

We going to release 2.0 soon but before that we need to organize some things, like dropping old branches.

**Comment by Flambe** [comment]
@gmsantos Should be good now. StyleCI is failing on docs I haven't touched, but I can fix if you want me too.

**Comment by gmsantos** [comment]
@Flambe dont worry, we can squash before merge :D

**Comment by gmsantos** [comment]
note: how mongo authentication are handled in that case

**Comment by diegofelix** [comment]
It's to hard to test this feature, for example, how do we handle database authentications per models? @Flambe Do you still want this feature, or I can close the PR?

**Comment by Flambe** [comment]
@diegofelix It's not needed by me any more, feel free to close it!

**Pull request closed without merging**
